#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
SUITE="trixie"
HATCHERY_SUITE="gila"

rm $CHROOT/etc/apt/sources.list
rm $CHROOT/etc/apt/sources.list.d/$HATCHERY_SUITE.list

cat << EOF > $CHROOT/etc/apt/sources.list.d/debian.sources
Types: deb
URIs: http://deb.debian.org/debian/
Suites: $SUITE
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: http://deb.debian.org/debian/
Suites: $SUITE-updates
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: http://security.debian.org/debian-security/
Suites: $SUITE-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF

cat << EOF > $CHROOT/etc/apt/sources.list.d/$HATCHERY_SUITE.sources
Types: deb
URIs: https://apt.hatcherylinux.org/
Suites: $HATCHERY_SUITE
Components: main
Signed-By: /etc/apt/trusted.gpg.d/$HATCHERY_SUITE.key.binary.gpg
EOF

exit 0
